# Generated by Django 3.2.15 on 2022-09-02 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='designation',
            field=models.CharField(default='Employee', max_length=250),
        ),
    ]
