# Generated by Django 3.2.15 on 2022-09-02 16:16

import asset_tracker.enums.approval_status
import asset_tracker.enums.asset_status
import asset_tracker.enums.category
import asset_tracker.enums.requested_needed
import asset_tracker.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('serial_number', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('amount', models.IntegerField(default=0)),
                ('category', models.CharField(choices=[('Laptop', 'LAPTOP'), ("Laptop's Charger", 'CHARGER'), ('Mobile', 'MOBILE'), ('Headphones', 'HEADPHONES'), ('Webcam', 'WEBCAM'), ('Mouse', 'MOUSE'), ('Keyboard', 'KEYBOARD')], default=asset_tracker.enums.category.Category['LAPTOP'], max_length=20)),
                ('category_type', models.CharField(max_length=20)),
                ('purchase_date', models.DateTimeField()),
                ('manufactured_date', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='asset_created_by', to=settings.AUTH_USER_MODEL)),
                ('update_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='asset_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AssetRequested',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_date', models.DateTimeField()),
                ('manager_approval', models.BooleanField(default=False)),
                ('reason', models.CharField(max_length=100)),
                ('approval_status', models.CharField(choices=[('Pending', 'PENDING'), ('Denied', 'DENIED'), ('Approved', 'APPROVED')], default=asset_tracker.enums.approval_status.ApprovalStatus['PENDING'], max_length=10)),
                ('request_needed', models.CharField(choices=[('New', 'NEW'), ('Repair', 'REPAIR'), ('Change', 'CHANGE')], default=asset_tracker.enums.requested_needed.RequestedNeeded['NEW'], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='asset_request_created_by', to=settings.AUTH_USER_MODEL)),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='asset_requested_by', to=settings.AUTH_USER_MODEL)),
                ('requested_to', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='asset_requested_to', to=settings.AUTH_USER_MODEL)),
                ('update_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='asset_request_update_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AssetFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback_date', models.DateTimeField()),
                ('feedback', models.CharField(max_length=100)),
                ('is_working', models.CharField(max_length=100)),
                ('productivity_rating', models.IntegerField(validators=[asset_tracker.models.AssetFeedback.validate_productivity_rating])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='asset_tracker.asset')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='asset_feedback_created_by', to=settings.AUTH_USER_MODEL)),
                ('feedback_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='asset_feedback_by', to=settings.AUTH_USER_MODEL)),
                ('update_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='asset_feedback_update_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AssetAssigned',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_date', models.DateTimeField()),
                ('asset_status', models.CharField(choices=[('In Use', 'IN_USE'), ('Discarded', 'DISCARDED'), ('Dispatched', 'DISPATCHED'), ('In stock', 'IN_STOCK'), ('In repairement', 'IN_REPAIRMENT')], default=asset_tracker.enums.asset_status.AssetStatus['IN_STOCK'], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='asset_approved_by', to=settings.AUTH_USER_MODEL)),
                ('assigned_asset', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='asset_tracker.asset')),
                ('assigned_to', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='asset_assigned_to', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='asset_assigned_created_by', to=settings.AUTH_USER_MODEL)),
                ('update_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='asset_assigned_update_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
