# Generated by Django 3.2.15 on 2022-09-02 18:51

import asset_tracker.enums.category
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset_tracker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetrequested',
            name='category',
            field=models.CharField(choices=[('Laptop', 'LAPTOP'), ("Laptop's Charger", 'CHARGER'), ('Mobile', 'MOBILE'), ('Headphones', 'HEADPHONES'), ('Webcam', 'WEBCAM'), ('Mouse', 'MOUSE'), ('Keyboard', 'KEYBOARD')], default=asset_tracker.enums.category.Category['LAPTOP'], max_length=20),
        ),
        migrations.AddField(
            model_name='assetrequested',
            name='category_type',
            field=models.CharField(default=asset_tracker.enums.category.Category['LAPTOP'], max_length=20),
        ),
        migrations.AlterField(
            model_name='asset',
            name='category_type',
            field=models.CharField(default=asset_tracker.enums.category.Category['LAPTOP'], max_length=20),
        ),
    ]
