# Generated by Django 3.2.15 on 2022-09-03 06:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset_tracker', '0002_auto_20220903_0021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='manufactured_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='asset',
            name='purchase_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='assetassigned',
            name='assigned_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='assetfeedback',
            name='feedback_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='assetrequested',
            name='requested_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
